baseURL = 'https://ali1609.github.io/lab_veille_blog/'
languageCode = 'en-us'
title = 'Branding Mania'
theme = "creative-portfolio"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Blog pour le cours LabVeilleTech"
  copyright = "© 2022"
  sidebarAbout = [
    "Ce blog a été créé dans le cadre du cours Laboratoire de Veille Technologique dispensé à la HEIG-VD, dans la filière Ingénierie des Médias. Le thème de ce blog est le Branding.",
    "Je suis Alison, étudiante en troisième année d'Ingénierie des Médias."
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Accueil"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "À propos"
  url = "about/"

